### ISSUE TITLE
A bit of help

### ISSUE THREAD

**Issue by Ceraun** [glua/gm_stringtable#5]
I would appreciate the skid comments being kept at a minimum, but would you mind aiding me. I can't seem to figure out how to get modules/stringtable.lua I haven't found the stringtable lua file anywhere on here.

**Comment by SwadicalRag** [comment]
Have you tried loading up gm_stringtable in visual studio 2015? Try building it, and when it asks for the "target container," input in "stringtable.lua".

I can't tell you any more, or the gmod police will come after me

**Comment by alexrsagen** [comment]
Usually that error appears when you haven't installed the binary module correctly. It must also be named appropriately.

`gmsv_stringtable_win32.dll` if you're using it on a windows server.
`gmcl_stringtable_win32.dll` if you're using it on a windows client.
`gmsv_stringtable_linux.dll` if you're running it on a linux server.

Just follow that naming scheme, then it'll load correctly.

The module must be placed in garrysmod/lua/bin

**Comment by 420BLAZEIT2MLG4U** [comment]
yerra fucken skid
i suggest you leave town come sunnup boy, else the buzzards'll be fightin' the lizards for yer gizzards.

now GIT

**Comment by Ceraun** [comment]
Sadly that hasn't solved my issue, it is installed as you have stated above, but there is no stringtable.lua in my modules folder, and the luaviewer.lua script is preventing my game from loading because of it. I can snip it out of my folder until you guys can reply, (If you don't mind helping out) Thanks very much for the effort put it

**Comment by HandsomeMatt** [comment]
you don't need a stringtable.lua file, just put the compiled DLL here
/lua/bin/gmcl_stringtable_win32.dll

**Comment by Ceraun** [comment]
Well I made a small change to the luaviewer script, and put require"luamio" in front, and I have the same problem with it. I am guessing the DLL's aren't being loaded before the script or maybe not at all? How would I get them to load?

**Comment by zerfgog** [comment]
skid comment

**Comment by HandsomeMatt** [comment]
you're annoying me now skid; just stop messing around editing files, get clean files and do what alexrsagen said

that's all you need to do
