### ISSUE TITLE
Hmmm I have a problem

### ISSUE THREAD

**Issue by Tekkie12** [glua/gm_stringtable#6]
Appearently the DLL's are named correctly, and placed in the correct location but are not being loaded.  Can anyone help me?

**Comment by zerfgog** [comment]
skid comment

**Comment by HandsomeMatt** [comment]
are you skids literally making alt accounts or what

**Comment by Tekkie12** [comment]
:/ so I see it is a bad idea to ask for help on here, sorry

**Comment by HandsomeMatt** [comment]
this isn't a help forum.
